# services:
#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: payapp
#       MYSQL_USER: payapp_user
#       MYSQL_PASSWORD: payapp_pass
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

#   backend:
#     build:
#       context: ./backend
#     container_name: payapp-backend
#     volumes:
#       - ./backend:/var/www/html
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"
#     command: >
#       sh -c "composer install &&
#              cp .env.example .env &&
#              php artisan key:generate &&
#              php artisan config:cache &&
#              php artisan migrate &&
#              php artisan serve --host=0.0.0.0 --port=8000"

#   frontend:
#     build:
#       context: ./frontend
#     container_name: payapp-frontend
#     volumes:
#       - ./frontend:/app
#     depends_on:
#       - backend
#     ports:
#       - "5173:5173"
#     command: >
#       sh -c "npm install && npm run dev -- --host"

# volumes:
#   db_data:

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payapp
      MYSQL_USER: payapp_user
      MYSQL_PASSWORD: payapp_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: payapp-backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "composer install &&
             cp .env.example .env &&
             php artisan key:generate &&
             php artisan config:cache &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
    container_name: payapp-frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules # Named volume for node_modules
    depends_on:
      - backend
    ports:
      - "5173:5173"
    # command: sh -c "npm install && npm run dev -- --host"
    command: sh -c "npm install && npx vite --host"

volumes:
  db_data:
  node_modules: # Add named volume
